package com.wise.baba.db.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.wise.baba.db.dao.Suggestion;

import com.wise.baba.db.dao.SuggestionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig suggestionDaoConfig;

    private final SuggestionDao suggestionDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        suggestionDaoConfig = daoConfigMap.get(SuggestionDao.class).clone();
        suggestionDaoConfig.initIdentityScope(type);

        suggestionDao = new SuggestionDao(suggestionDaoConfig, this);

        registerDao(Suggestion.class, suggestionDao);
    }
    
    public void clear() {
        suggestionDaoConfig.getIdentityScope().clear();
    }

    public SuggestionDao getSuggestionDao() {
        return suggestionDao;
    }

}
