package com.wise.baba.db.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.wise.baba.db.dao.HistorySearch;

import com.wise.baba.db.dao.HistorySearchDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig historySearchDaoConfig;

    private final HistorySearchDao historySearchDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        historySearchDaoConfig = daoConfigMap.get(HistorySearchDao.class).clone();
        historySearchDaoConfig.initIdentityScope(type);

        historySearchDao = new HistorySearchDao(historySearchDaoConfig, this);

        registerDao(HistorySearch.class, historySearchDao);
    }
    
    public void clear() {
        historySearchDaoConfig.getIdentityScope().clear();
    }

    public HistorySearchDao getHistorySearchDao() {
        return historySearchDao;
    }

}
