package com.wise.baba.db.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SUGGESTION.
 */
public class Suggestion {

    private Integer type;
    private String key;
    private String city;
    private String district;

    public Suggestion() {
    }

    public Suggestion(Integer type, String key, String city, String district) {
        this.type = type;
        this.key = key;
        this.city = city;
        this.district = district;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getDistrict() {
        return district;
    }

    public void setDistrict(String district) {
        this.district = district;
    }

}
